### ISSUE TITLE
Impossible to post combined emojis in chat

### ISSUE THREAD

**Issue by TETYYS** [twitchdev/issues#307]
**Brief description**
\u200D is impossible to post in chat because the character gets filtered out

**How to reproduce**
Post 👨‍🌾

**Expected behavior**
See 👨‍🌾. Posting it also gives false impressions in webchat because it gets rendered properly immediately client-side, but all other chatters see broken emojis.

**Screenshots**
![WindowsTerminal_Z5WgpsAWEH](https://user-images.githubusercontent.com/3091645/107766146-b7423680-6d3b-11eb-9ded-09a905d6eec8.png) (left is poster, right is viewer)

**Comment by lleadbet** [comment]
Ticketed internally as MES-5018.

**Comment by Mm2PL** [comment]
It's also impossible to post some flags, for example Scotland: expected: `🏴󠁧󠁢󠁳󠁣󠁴󠁿`, actual: `🏴`. These apparently use different characters than ZWJ (U+200D).

**Comment by ErisApps** [comment]
@lleadbet Any news on this issue?

I also recently opened [a UserVoice](https://twitch.uservoice.com/forums/310201-chat/suggestions/44425005-lots-of-unicode-emojis-being-broken-due-to-zwj-bei) regarding this issue, and also stumbled upon [this post](https://discuss.dev.twitch.tv/t/chat-emoji-issue/24803) shortly after posting said UserVoice.

Anyways, this issue affects roughly 37,8% (1329 out of 3512) of all Unicode 13.1 specified emojis. Attached also an extract of the ones that are affected. (Full list of emotes can be found here: https://www.unicode.org/Public/emoji/13.1/emoji-test.txt )
[BrokenEmojisOnTwitch.txt](https://github.com/twitchdev/issues/files/7530244/BrokenEmojisOnTwitch.txt)

**Comment by ErisApps** [comment]
> It's also impossible to post some flags, for example Scotland: expected: `🏴󠁧󠁢󠁳󠁣󠁴󠁿`, actual: `🏴`. These apparently use different characters than ZWJ (U+200D).

Regarding this issue. I could easily reproduce this myself by sending the flag of either England, Scotland or Wales and intercepting the websocket response in another browser.

It seems like for those 3 emotes, all modifiers get stripped, leaving only `\u1F3F4`, which represents a bare black flag instead.
Below also the full sequence of each flag respectively (which can also be found in the full emoji-test.txt document linked in my previous post)

### subgroup: subdivision-flag
1F3F4 E0067 E0062 E0065 E006E E0067 E007F              ; fully-qualified     # 🏴󠁧󠁢󠁥󠁮󠁧󠁿 E5.0 flag: England
1F3F4 E0067 E0062 E0073 E0063 E0074 E007F              ; fully-qualified     # 🏴󠁧󠁢󠁳󠁣󠁴󠁿 E5.0 flag: Scotland
1F3F4 E0067 E0062 E0077 E006C E0073 E007F              ; fully-qualified     # 🏴󠁧󠁢󠁷󠁬󠁳󠁿 E5.0 flag: Wales

**Comment by Felanbird** [comment]
@lleadbet Do you mind looking into this ticket? It seems the issue has been resolved, but whether or not it's intentional or a side-effect of another change is unknown.

**Comment by ErisApps** [comment]
> > It's also impossible to post some flags, for example Scotland: expected: `🏴󠁧󠁢󠁳󠁣󠁴󠁿`, actual: `🏴`. These apparently use different characters than ZWJ (U+200D).
> 
> Regarding this issue. I could easily reproduce this myself by sending the flag of either England, Scotland or Wales and intercepting the websocket response in another browser.
> 
> It seems like for those 3 emotes, all modifiers get stripped, leaving only `\u1F3F4`, which represents a bare black flag instead. Below also the full sequence of each flag respectively (which can also be found in the full emoji-test.txt document linked in my previous post)
> ### subgroup: subdivision-flag
> 
> 1F3F4 E0067 E0062 E0065 E006E E0067 E007F ; fully-qualified # 🏴󠁧󠁢󠁥󠁮󠁧󠁿 E5.0 flag: England
> 1F3F4 E0067 E0062 E0073 E0063 E0074 E007F ; fully-qualified # 🏴󠁧󠁢󠁳󠁣󠁴󠁿 E5.0 flag: Scotland
> 1F3F4 E0067 E0062 E0077 E006C E0073 E007F ; fully-qualified # 🏴󠁧󠁢󠁷󠁬󠁳󠁿 E5.0 flag: Wales

Emojis that rely on the ZWJ (U+200D) character, do seem to work properly now (or at least the few that I used to test). However, the 3 flag emojis above seemingly still don't work, they still get their additional modifiers stripped.

**Comment by jbulava** [comment]
@Felanbird Yes, the internal tracking ticket that was mentioned above was resolved 2 weeks ago.  So it was an intentional fix.

@ErisApps I will raise the flag (pun intended) issue with the chat team in case there are some further intricacies to look into. Thanks.

**Comment by Xemdo** [comment]
Noting that the issue for the Scotland flag still exists. We're currently investigating this.

**Comment by Xemdo** [comment]
Ticketed internally (again) as CFC-9244
