### ISSUE TITLE
Permissions _just don't work_ if a newly release if the test version was installed

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#359]
**Brief description**

Capability permissions "die" on a newly released extension (no prior versions) if that channel had the test version installed

**How to reproduce**

If you are building an extension.
During the building you may get the test version of the extension installed to an affliate or partner channel.
Then when you get your extension reviewed and release it, it being the first ever version.

Said affiliate/partner will now have the released version.

However, in some cases one or more of the permissions for subs/chat send/bits enabled capabilities become broken and forced off.
The afiliate/partner cannot use the manage permissions UI to toggle the permission on.
Generally the only fix for the issue is to completely uninstall the extension and reinstall it.

**Expected behavior**

Permissions not to asplode

**Additional context or questions**

I have observed it myself.
With "chat" often not working for no reason, until extension reinstall

Most recently in Discord at https://discord.com/channels/504015559252377601/523676096277905419/825077875547176986 we are yet to resolve this instance of this bug.

And it does periodically popup in Discord as a issue people have and a reinstall resolves

**Comment by BarryCarlyon** [comment]
To update

I released a new version of an extension today.
Where the test version was installed on the same channel

All the permissions are locked off and cannot be turned on without a reinstall of the extension to the channel.

So it's not limited to first release.
It occurs with a channel having the test version intalled and the "real" version being released.

**Comment by jbulava** [comment]
Ticketed internally as ANC-2796.

**Comment by Hades32** [comment]
@jbulava it has been more than a year. Is this not fixed yet?

**Comment by p4dd9** [comment]
I have experienced the same issue on a newly released extension (first release). The permission toggle resolved itself after uninstalling and installing the extension. https://discord.com/channels/504015559252377601/523676096277905419/1248871716944347178

**Comment by Slruh** [comment]
Also hit this was my new extension that was just released. The work around of uninstalling and reinstalling works but it gave me quite the heart attack.

**Comment by bamboechop** [comment]
Since we have 2026 now and I just ran into this I figured I'll leave a comment as well in hopes that this might either be prioritized or at least a hint is added to the release process that informs about this bug and the workaround to get the permissions working again.

**Comment by mbayou** [comment]
We are experiencing the same issue, hoping to bump this one up.
