### ISSUE TITLE
Get Channel Teams: Null instead of [] if no teams

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#495]
**Brief description**

https://dev.twitch.tv/docs/api/reference#get-channel-teams

if a channel is not in any teams, the API responds

> {"data":null}

Instead of 

> {"data":[]}

**How to reproduce**

Call Get Channel teams for a channel that is in no teams

**Expected behavior**

Empty array instead of null

**Comment by Emilgardis** [comment]
The docs says that 404 should be returned when "The broadcaster is not a member of a team."

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1502855/216788871-d49faa03-224c-4bcd-bce4-6f838892fd0e.png">

**Comment by BarryCarlyon** [comment]
Then the documentation is wrong. as currently this bug is _fixed_ and the result is 

```
twitch api get 'teams/channel?broadcaster_id=56410307'
{
  "data": []
}
```

**Comment by Emilgardis** [comment]
I get null when using a real call and not twitch-cli

**Comment by Emilgardis** [comment]
```
❯ twitch api get teams/channel -q broadcaster_id=1234
{
  "data": []
}
```

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1502855/216789870-535e5d95-54c4-4e6e-a9da-1166c9be31b3.png">

I think twitch-cli is normalizing it

**Comment by BarryCarlyon** [comment]
Ok so why did you add a comment suggest the issue was fixed but the docs say 404?

**Comment by Emilgardis** [comment]
The comment was to the expected behaviour. The docs says 404, your expected result is an empty array (which is my prefered behaviour aswell) and the actual behaviour is null.

**Comment by talk2MeGooseman** [comment]
The bug is still active instead of an empty array receiving the following:

```
curl 'https://api.twitch.tv/helix/teams/channel?broadcaster_id=120750024'

{"data":null}
```

I believe this bug has been triggered by a person who is part of a team(s) being banned, and their account is reinstated.

**Comment by Xemdo** [comment]
Tested it with a bunch of recently banned accounts, and again with 120750024. Can't reproduce the null value.
However the empty array still happens:
```
> twitch api get teams/channel -q broadcaster_id=57047445
{
  "data": []
}
```

And I found another bug where it returns HTTP 500 instead of 404 if the user cannot be found. Will open that up as another ticket.

**Comment by Xemdo** [comment]
Actually, it seems it showing the empty array is purely from the Twitch CLI. Running it with curl shows a null value, even for accounts that aren't banned (such as mine).

Ticketed internally as ASYNC-3967

**Comment by Xemdo** [comment]
Fixed as of November 2023.
