### ISSUE TITLE
Developer Console - Can't add new application

### ISSUE THREAD

**Issue by Chykary** [twitchdev/issues#634]
**Brief description**
It no longer seems to be possible to create a new application in the Dev Console.

**How to reproduce**
1. Go to https://dev.twitch.tv/console/apps/create
2. Try to create an application

**Expected behavior**
Application is created and you can use the secret to hook up your app.

**Screenshots**
<img width="534" alt="TwitchErr-1" src="https://user-images.githubusercontent.com/30300243/181524663-f3be75a4-f4c4-4aa8-80fd-6d93cc930b45.png">

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
This should be resolved (it was reported and fixed late yesteday)

Can you retest and confirm?

**Comment by Chykary** [comment]
Unfortunately the error still persists. I had two different people try to create an app with different machines & networks and no avail.

**Comment by Syzuna** [comment]
Does the name of the application you are trying to create contain "Twitch" or "Extension" or sth like that?

**Comment by Chykary** [comment]
It does not, no:

![image](https://user-images.githubusercontent.com/30300243/181654438-b7cee415-8fa1-424a-a42a-11dcb96f3957.png)

(Doesn't work with other random names either)

**Comment by Syzuna** [comment]
Well turns out my working version seemed to be a cached one.
After I switched my language to german just to be a 100% sure, and that killed my old cached version, it fails on german and english with the same error now.

**Comment by KWLuna** [comment]
I'm also having the same issue
I've reached out for help at https://discuss.dev.twitch.tv/t/create-application-button-not-working/39831?u=luna and attempted the suggestions as well.

![image](https://user-images.githubusercontent.com/42366824/182126990-17475cbf-8e6a-4895-9002-1aebd0170372.png)

**Comment by Gabo6480** [comment]
Having same problem as well

**Comment by Gabo6480** [comment]
Looks like it has to do with the "Game Integration" category, if you change it to anything else it works adequately

**Comment by Chykary** [comment]
Ah, thanks for the hint, I was able to create an app with another category - however it still does not store the organization, and sets it to "None" even if you selected one.

**Comment by BarryCarlyon** [comment]
Various reports saying that this is also effecting extension client ID creation

**Comment by MelleJ** [comment]
Having the exact same issues as noted in #638 but adding onto this as 'main' issue.

Unable to make a new extension in anyway, no name is going through.

**Comment by jbulava** [comment]
The team is aware of this issue and has identified a few reasons for application creation to be causing errors.  Most of these issues should have been resolved with a fix deployed today, but please let us know if there are certain conditions where are you are still not able to create applications or Extensions.

**Comment by MelleJ** [comment]
Thanks for the quick reply! Sadly I still seem to be unable to create an extension, I have not checked out the application creation. See the screenshots below. Using Mozilla Firefox 103.0.1 (64-bit) on a Windows 10 (64-bit) machine.

![image](https://user-images.githubusercontent.com/20356891/183246140-a19be638-43c6-4dd2-a858-e03b60e253d8.png)
![image](https://user-images.githubusercontent.com/20356891/183246118-321066c5-92cb-42c8-876f-14420a3bb747.png)

**Comment by RoccoNatuzzi** [comment]
Problem still persist also for me

**Comment by Lunatunny** [comment]
Same here.

**Comment by chris-lu** [comment]
Still occurring.

**Comment by MelleJ** [comment]
Managed to get through this morning! Not sure why it worked now (if you guys fixed something), but solved for me atleast :)

**Comment by jbulava** [comment]
Great to hear! An additional fix was deployed yesterday afternoon and we below that application and Extension creation has been corrected.  We will leave this issue open for a few more days in case there are instances still occurring.  If that is the case, please be as specific as possible to help reproduce the issue.  Thanks.

**Comment by Jabark** [comment]
I have a similar issue, I can and have created an application, however now I cannot edit it
![image](https://user-images.githubusercontent.com/9607853/193269214-aa94e1a8-fab6-4d33-960f-050964d1cb48.png)

**Comment by JACaddock** [comment]
I'm also having the same errors

**Comment by yash1441** [comment]
The issue still persists. Cannot create new or edit existing applications.

**Comment by BarryCarlyon** [comment]
This is superseeded by #665 and anyone having an issue crate or editing an application should also check they are

1) using a supported browser (Chrome/Firefox/Edge/Safari) Brave or operaGX users may have issues
b) ensure your application is using a unique name that adequately identifies your application.

**Comment by yash1441** [comment]
> This is superseeded by #665 and anyone having an issue crate or editing an application should also check they are
> 
> 1. using a supported browser (Chrome/Firefox/Edge/Safari) users of: Brave or operaGX users may have issues
> 2. ensure your application is using a unique name that adequately identifies your application.

1. Using Edge.
2. Tried using a very specific and unique name.

Getting `failed integrity check`.

**Comment by domsson** [comment]
I can neither create a new, nor edit an existing application. Have tried with two different browsers and two different users (one combination of which was previously able to create and edit applications). Getting GraphSQL error in the console.

**Comment by StEaLtHmAn** [comment]
I figured it out after hours wasted.

The name may not contain certain words. Most notably the word "twitch". It doesn't tell you that you can't use these words so the error is just that it doesn't tell you the error or any message to indicate you not to use certain words.

**Comment by domsson** [comment]
> The name may not contain certain words. 

That seems to check out from my own struggles. The word "Drops" also seems to trigger it. However, this doesn't seem to be the only issue. It also seems that choosing "Game integration" as category will result in the error, no matter the title. I believe this because I was able to use a certain Title once I selected "Website integration", but the _same_ title would give an error if "Game integration" was shown. Also, I couldn't find _any_ title that would work when that category was selected.

**Comment by jbulava** [comment]
There was a known issue last week regarding the creation of an application when selecting "game integration" as the type.  This issue has been corrected.

**Comment by jbulava** [comment]
Given the title of this bug report is broad and the original issue was resolved, I will lock this conversation. New issues that arise when creating an application should be tracked as new GitHub Issues for teams to be aware. Should you find this specific thread in the future (hello there), please create a new GitHub Issue with as much specific detail as possible.
