### ISSUE TITLE
EventSub Reference duplicated content

### ISSUE THREAD

**Issue by theca11** [twitchdev/issues#912]
**Brief description**
The [EventSub Reference](https://dev.twitch.tv/docs/eventsub/eventsub-reference/) has some content duplicated as can be easily seen in the left navigation bar. The first section seems to be the bad one, or at least the `Events` part is highly incomplete (only 4 events there)

**Expected documentation**
No duplications

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/48060851/a9d08608-7a7f-4071-9de7-90bf3eb443a6)

**Comment by Xemdo** [comment]
Fixed

**Comment by theca11** [comment]
I don't see it fixed, not sure if something has to rollout still

**Comment by theca11** [comment]
FYI, after a week the issue is still present. Not the most important issue whatsoever, but just letting you know

**Comment by Xemdo** [comment]
Should be solved now. The deploy was delayed
